name: Build check

on:
  push:
    branches-ignore:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    name: Build check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          cat package.json
          npm cache clean --force
          npm install

      - name: Build website
        env:
          NODE_OPTIONS: "--max-old-space-size=6144"
        run: |
          make build

