name: Build And Deploy

on:
  push:
    branches:
      - 'main'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: |
          yarn

      - name: Generate contributors
        run: |
          bash .github/workflows/generate-contributors.sh

      - name: Generate docs changelog
        run: |
          bash .github/workflows/generate-changelog.sh

      - name: Build website
        run: |
          make build

      # https://github.com/appleboy/scp-action
      - name: Deploy to - goframe.org
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: './build/*'
          target: '/home/www/goframe.org'
          strip_components: 1
          rm: true

      - name: Deploy to - goframe.org.cn
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST_CN }}
          username: ${{ secrets.SSH_USERNAME_CN }}
          password: ${{ secrets.SSH_PASSWORD_CN }}
          port: ${{ secrets.SSH_PORT_CN }}
          source: './build/*'
          target: '/home/www/goframe.org.cn'
          strip_components: 1
          rm: true

      - name: Deploy to - pages.goframe.org
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: pages.goframe.org
